import uuid
import json
import datetime
from dataclasses import dataclass, field, asdict, replace
from typing import Any, Callable, List, Mapping, MutableMapping, Optional, Dict, Union

from pydantic import BaseModel, Field, ValidationError

# ----------------------------------------------------------------------
# Exceptions
# ----------------------------------------------------------------------


class ConfigurationError(Exception):
    """Raised when the user supplied configuration is invalid or incomplete."""

    pass


class EvaluationError(Exception):
    """Raised when a metric evaluation fails during a trial."""

    pass


# ----------------------------------------------------------------------
# Data models
# ----------------------------------------------------------------------


@dataclass
class PromptCandidate:
    """A concrete prompt generated by an LLM driver.

    Attributes
    ----------
    id: str
        Unique identifier for the candidate.
    prompt: str
        The actual prompt text.
    metadata: Mapping[str, Any]
        Arbitrary driver‑specific information (e.g., token usage).
    """

    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    prompt: str = ""
    metadata: Mapping[str, Any] = field(default_factory=dict)

    def as_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class TrialResult:
    """Result of evaluating a single `PromptCandidate`.

    Attributes
    ----------
    candidate_id: str
        Identifier of the candidate that was evaluated.
    metrics: Mapping[str, float]
        Mapping of metric name to its computed value.
    success: bool
        Whether the trial completed without raising an `EvaluationError`.
    error: Optional[str]
        Human‑readable error message if `success` is ``False``.
    timestamp: datetime.datetime
        When the trial finished.
    """

    candidate_id: str
    metrics: Mapping[str, float]
    success: bool = True
    error: Optional[str] = None
    timestamp: datetime.datetime = field(default_factory=datetime.datetime.utcnow)

    def as_dict(self) -> Dict[str, Any]:
        data = asdict(self)
        data["timestamp"] = self.timestamp.isoformat()
        return data


class OptimizationConfig(BaseModel):
    """Pydantic model describing the optimisation plan.

    The YAML manifest is parsed into this model. It contains the target
    callable, the list of metrics to optimise for, the LLM driver to use, and
    optional hyper‑parameters such as the number of trials.
    """

    target_path: str = Field(..., description="Python dotted path to the function to optimise.")
    metrics: List[str] = Field(..., description="Names of metrics to evaluate each candidate.")
    driver: str = Field(..., description="Name of the registered LLM driver to use.")
    max_trials: int = Field(10, description="Maximum number of optimisation iterations.")
    backoff_factor: float = Field(0.5, description="Base factor for exponential back‑off retries.")

    class Config:
        extra = "forbid"

# Compatibility alias used by older code
Trial = TrialResult
