import { z } from "zod";

/**
 * Zod schema for the metadata of a prompt.
 * Represents the contents of a `meta.json` file.
 */
export const PromptMetaSchema = z.object({
  /** Unique slug derived from the file path */
  id: z.string(),
  /** Human readable name */
  title: z.string(),
  /** Short summary used for search */
  description: z.string(),
  /** Classification keywords */
  tags: z.array(z.string()),
  /** Relative path to preview.png */
  previewImage: z.string(),
  /** Optional attribution */
  author: z.string().optional(),
  /** Optional link to original prompt */
  sourceUrl: z.string().url().optional(),
});

/** Type representing a prompt's metadata. */
export type PromptMeta = z.infer<typeof PromptMetaSchema>;

/**
 * Zod schema for the code generated by an LLM.
 * The `files` map contains filenames (e.g. `App.tsx`) mapped to their source content.
 */
export const GeneratedCodeSchema = z.object({
  /** Map of filename → file content (TSX, CSS, etc.) */
  files: z.record(z.string()),
  /** Provenance information */
  metadata: z.object({
    /** Identifier of the model that generated the code */
    modelId: z.string(),
    /** Unix epoch in milliseconds */
    timestamp: z.number(),
  }),
});

/** Type representing generated source files and provenance metadata. */
export type GeneratedCode = z.infer<typeof GeneratedCodeSchema>;

/**
 * Zod schema for a bundled JavaScript payload produced by the sandbox compiler.
 * The bundle is a self‑contained script that can be executed inside an iframe.
 */
export const BundleSchema = z.object({
  /** The bundled JavaScript code as a string */
  code: z.string(),
  /** Optional source map for debugging */
  map: z.string().optional(),
});

/** Type representing a compiled bundle ready for execution. */
export type Bundle = z.infer<typeof BundleSchema>;

/**
 * Zod schema for a user edit operation.
 * The UI sends this object to the engine when a prompt markdown is changed.
 */
export const PromptEditSchema = z.object({
  /** Identifier of the prompt being edited */
  id: z.string(),
  /** Full markdown content after the edit */
  markdown: z.string(),
});

/** Type representing a prompt edit coming from the UI. */
export type PromptEdit = z.infer<typeof PromptEditSchema>;

/**
 * Zod schema for optional generation parameters passed to the AI provider.
 */
export const GenerationOptionsSchema = z.object({
  /** Controls randomness; 0 = deterministic */
  temperature: z.number().min(0).max(2).optional(),
  /** Maximum number of tokens to generate */
  maxTokens: z.number().int().positive().optional(),
  /** Nucleus sampling probability */
  topP: z.number().min(0).max(1).optional(),
});

/** Type representing optional generation options for the AI client. */
export type GenerationOptions = z.infer<typeof GenerationOptionsSchema>;

/**
 * Zod schema for the result of a sandboxed preview.
 * Contains a blob URL that can be embedded in an iframe and any runtime errors.
 */
export const PreviewResultSchema = z.object({
  /** Blob URL of the sandboxed preview */
  iframeUrl: z.string().url(),
  /** Captured console errors during execution */
  runtimeErrors: z.array(z.string()),
  /** How long the bundle took to mount, in milliseconds */
  renderTimeMs: z.number(),
});

/** Type representing the outcome of a sandbox execution. */
export type PreviewResult = z.infer<typeof PreviewResultSchema>;

/**
 * Utility function that validates an unknown object against the PromptMeta schema.
 * Throws a ZodError if validation fails.
 *
 * @param data - The raw object to validate.
 * @returns A strongly typed PromptMeta instance.
 */
export function parsePromptMeta(data: unknown): PromptMeta {
  return PromptMetaSchema.parse(data);
}

/**
 * Utility function that validates an unknown object against the GeneratedCode schema.
 *
 * @param data - The raw object to validate.
 * @returns A strongly typed GeneratedCode instance.
 */
export function parseGeneratedCode(data: unknown): GeneratedCode {
  return GeneratedCodeSchema.parse(data);
}

/**
 * Utility function that validates an unknown object against the Bundle schema.
 *
 * @param data - The raw object to validate.
 * @returns A strongly typed Bundle instance.
 */
export function parseBundle(data: unknown): Bundle {
  return BundleSchema.parse(data);
}

/**
 * Utility function that validates an unknown object against the PromptEdit schema.
 *
 * @param data - The raw object to validate.
 * @returns A strongly typed PromptEdit instance.
 */
export function parsePromptEdit(data: unknown): PromptEdit {
  return PromptEditSchema.parse(data);
}

/**
 * Utility function that validates an unknown object against the GenerationOptions schema.
 *
 * @param data - The raw object to validate.
 * @returns A strongly typed GenerationOptions instance.
 */
export function parseGenerationOptions(data: unknown): GenerationOptions {
  return GenerationOptionsSchema.parse(data);
}

/**
 * Utility function that validates an unknown object against the PreviewResult schema.
 *
 * @param data - The raw object to validate.
 * @returns A strongly typed PreviewResult instance.
 */
export function parsePreviewResult(data: unknown): PreviewResult {
  return PreviewResultSchema.parse(data);
}

/**
 * Helper type that extracts the keys of a Zod schema as a union of string literals.
 *
 * @template T - Zod schema type.
 */
export type SchemaKeys<T extends z.ZodTypeAny> = keyof T["_output"];

/**
 * Deep partial version of any Zod-derived type.
 * Useful for patch updates where only a subset of fields is provided.
 *
 * @template T - Original type.
 */
export type DeepPartial<T> = {
  [P in keyof T]?: T[P] extends object ? DeepPartial<T[P]> : T[P];
};

/**
 * Export a consolidated object that groups all schemas.
 * This can be imported by modules that need runtime validation without pulling individual symbols.
 */
export const Schemas = {
  PromptMeta: PromptMetaSchema,
  GeneratedCode: GeneratedCodeSchema,
  Bundle: BundleSchema,
  PromptEdit: PromptEditSchema,
  GenerationOptions: GenerationOptionsSchema,
  PreviewResult: PreviewResultSchema,
} as const;

/**
 * Runtime guard that checks whether a given object conforms to the PromptMeta shape.
 *
 * @param obj - Object to test.
 * @returns `true` if the object matches PromptMeta, otherwise `false`.
 */
export function isPromptMeta(obj: unknown): obj is PromptMeta {
  return PromptMetaSchema.safeParse(obj).success;
}

/**
 * Runtime guard that checks whether a given object conforms to the GeneratedCode shape.
 *
 * @param obj - Object to test.
 * @returns `true` if the object matches GeneratedCode, otherwise `false`.
 */
export function isGeneratedCode(obj: unknown): obj is GeneratedCode {
  return GeneratedCodeSchema.safeParse(obj).success;
}

/**
 * Runtime guard that checks whether a given object conforms to the Bundle shape.
 *
 * @param obj - Object to test.
 * @returns `true` if the object matches Bundle, otherwise `false`.
 */
export function isBundle(obj: unknown): obj is Bundle {
  return BundleSchema.safeParse(obj).success;
}

/**
 * Runtime guard that checks whether a given object conforms to the PreviewResult shape.
 *
 * @param obj - Object to test.
 * @returns `true` if the object matches PreviewResult, otherwise `false`.
 */
export function isPreviewResult(obj: unknown): obj is PreviewResult {
  return PreviewResultSchema.safeParse(obj).success;
}