import Foundation
import Metal
import os.log

/// Errors that can be raised during an inference session.
public enum InferenceError: Error, CustomStringConvertible {
    /// Non‑recoverable error that aborts the whole session.
    case fatal(message: String)
    /// Transient error that may be retried.
    case transient(message: String, underlying: Error)

    public var description: String {
        switch self {
        case .fatal(let message):
            return "Fatal InferenceError: \(message)"
        case .transient(let message, let underlying):
            return "Transient InferenceError: \(message) – underlying: \(underlying)"
        }
    }
}

/// Executes inference using fused kernels generated by ``KernelFusionBuilder``.
public final class InferenceEngine {
    private let device: MTLDevice
    private let commandQueue: MTLCommandQueue
    private let logger = OSLog(subsystem: "com.metalmoe.inference", category: "InferenceEngine")

    public init(device: MTLDevice) throws {
        self.device = device
        guard let queue = device.makeCommandQueue() else {
            throw InferenceError.fatal(message: "Unable to create Metal command queue.")
        }
        self.commandQueue = queue
    }

    /// Runs a single inference step.
    /// - Parameter inputBuffer: Buffer containing input tokens.
    /// - Returns: Buffer with output logits.
    /// - Throws: `InferenceError` on failure.
    public func runInference(inputBuffer: MTLBuffer) throws -> MTLBuffer {
        // Placeholder implementation: simply returns the input buffer.
        // A real implementation would dispatch a fused kernel built by KernelFusionBuilder.
        os_log("Running inference step.", log: logger, type: .info)
        return inputBuffer
    }
}
