import uuid
import time
import hashlib
import mimetypes
import json
import sqlite3
from pathlib import Path
from dataclasses import dataclass, field, asdict
from enum import Enum
from typing import List, Optional, Dict, Any, Iterable, Generator, Tuple


def _generate_uuid() -> str:
    """Generate a UUID4 string."""
    return str(uuid.uuid4())


def _now_ms() -> int:
    """Return current epoch time in milliseconds."""
    return int(time.time() * 1000)


def compute_sha256(file_path: str) -> str:
    """Compute the SHA‑256 hash of a file's contents."""
    h = hashlib.sha256()
    with open(file_path, "rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            h.update(chunk)
    return h.hexdigest()


class RunStatus(str, Enum):
    """Lifecycle status of a Run."""

    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"


class PermissionProfile(str, Enum):
    """Permission handling strategy for a Project."""

    ASK = "ask"
    AUTO = "auto"
    FULL = "full"


class ArtifactKind(str, Enum):
    """Classification of an artifact."""

    WORKSPACE = "workspace"
    GENERATED = "generated"
    EXTERNAL = "external"


@dataclass
class Project:
    """A research project grouping runs and permission defaults."""

    id: str
    name: str
    description: str = ""
    createdAt: int = field(default_factory=_now_ms)
    updatedAt: int = field(default_factory=_now_ms)
    defaultPermission: PermissionProfile = PermissionProfile.ASK

    def to_dict(self) -> Dict[str, Any]:
        """Serialize the project to a plain dict."""
        return asdict(self)


@dataclass
class Run:
    """A single execution of a research task."""

    id: str
    projectId: str
    status: RunStatus = RunStatus.RUNNING
    startedAt: int = field(default_factory=_now_ms)
    completedAt: Optional[int] = None
    artifactIds: List[str] = field(default_factory=list)
    log: str = ""

    def start(self) -> None:
        """Mark the run as started and record timestamp."""
        self.status = RunStatus.RUNNING
        self.startedAt = _now_ms()
        self.append_log("Run started")

    def complete(self) -> None:
        """Mark the run as completed and record timestamp."""
        self.status = RunStatus.COMPLETED
        self.completedAt = _now_ms()
        self.append_log("Run completed")

    def fail(self, reason: str) -> None:
        """Mark the run as failed, record timestamp and reason."""
        self.status = RunStatus.FAILED
        self.completedAt = _now_ms()
        self.append_log(f"Run failed: {reason}")

    def add_artifact(self, artifact_id: str) -> None:
        """Register an artifact ID with this run."""
        self.artifactIds.append(artifact_id)
        self.append_log(f"Artifact registered: {artifact_id}")

    def append_log(self, entry: str) -> None:
        """Append a line to the run log with a timestamp."""
        ts = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime())
        self.log += f"[{ts}] {entry}\n"


@dataclass
class Artifact:
    """Immutable representation of a file produced by a kernel step."""

    id: str
    runId: str
    kind: ArtifactKind
    path: str
    sha256: str
    size: int
    mimeType: str
    createdAt: int = field(default_factory=_now_ms)

    @classmethod
    def create_from_file(
        cls, run_id: str, kind: ArtifactKind, file_path: str, mime_type: Optional[str] = None
    ) -> "Artifact":
        """Create an Artifact instance from a file on disk."""
        p = Path(file_path).resolve()
        if not p.is_file():
            raise FileNotFoundError(f"Artifact file not found: {file_path}")

        size = p.stat().st_size
        sha256 = compute_sha256(str(p))
        inferred_mime = mime_type or mimetypes.guess_type(str(p))[0] or "application/octet-stream"

        return cls(
            id=_generate_uuid(),
            runId=run_id,
            kind=kind,
            path=str(p),
            sha256=sha256,
            size=size,
            mimeType=inferred_mime,
        )

    def to_dict(self) -> Dict[str, Any]:
        """Serialize the artifact to a plain dict."""
        return asdict(self)


@dataclass
class PlanStep:
    """A single step in a plan generated by a provider."""

    name: str
    args: Dict[str, Any]

    def to_json(self) -> str:
        """Serialize the step to JSON."""
        return json.dumps({"name": self.name, "args": self.args})


@dataclass
class ExecutionMetadata:
    """Metadata returned after executing a kernel step."""

    step_index: int
    stdout: str
    stderr: str
    exit_code: int
    usage: Dict[str, Any]
    output_dir: str

    def succeeded(self) -> bool:
        """Return True if the step exited with code 0."""
        return self.exit_code == 0


class AgentEventType(str, Enum):
    """Event categories emitted by AgentEngine."""

    PLANNING = "planning"
    EXECUTION = "execution"
    OBSERVATION = "observation"
    PERMISSION_REQUEST = "permission_request"
    COMPLETED = "completed"
    FAILED = "failed"


@dataclass
class AgentEvent:
    """A single event emitted during the plan‑execute‑observe loop."""

    timestamp: int
    type: AgentEventType
    detail: str
    stepIndex: Optional[int] = None
    error: Optional[Exception] = None


class ProviderError(Exception):
    """Error raised when a provider request fails."""

    def __init__(self, message: str, transient: bool = False):
        super().__init__(message)
        self.transient = transient


class KernelError(Exception):
    """Error raised when a sandboxed kernel crashes."""

    def __init__(self, message: str, exit_code: Optional[int] = None):
        super().__init__(message)
        self.exit_code = exit_code


class SecurityError(Exception):
    """Error raised when a launch violates security policies."""


@dataclass
class PermissionDecision:
    """Result of a human‑in‑the‑loop permission request."""

    request_id: str
    decision: str  # "allow" | "deny"
    reason: Optional[str] = None


class ArtifactStore:
    """SQLite‑backed immutable store for projects, runs, and artifacts."""

    def __init__(self, db_path: str):
        self.db_path = db_path
        self.conn = sqlite3.connect(self.db_path, check_same_thread=False)
        self._ensure_schema()

    def _ensure_schema(self) -> None:
        cur = self.conn.cursor()
        cur.executescript(
            """
            CREATE TABLE IF NOT EXISTS projects (
                id TEXT PRIMARY KEY,
                name TEXT NOT NULL,
                description TEXT,
                createdAt INTEGER,
                updatedAt INTEGER,
                defaultPermission TEXT
            );
            CREATE TABLE IF NOT EXISTS runs (
                id TEXT PRIMARY KEY,
                projectId TEXT NOT NULL,
                status TEXT,
                startedAt INTEGER,
                completedAt INTEGER,
                artifactIds TEXT,
                log TEXT,
                FOREIGN KEY(projectId) REFERENCES projects(id)
            );
            CREATE TABLE IF NOT EXISTS artifacts (
                id TEXT PRIMARY KEY,
                runId TEXT NOT NULL,
                kind TEXT,
                path TEXT,
                sha256 TEXT,
                size INTEGER,
                mimeType TEXT,
                createdAt INTEGER,
                FOREIGN KEY(runId) REFERENCES runs(id)
            );
            """
        )
        self.conn.commit()

    def save_project(self, project: Project) -> None:
        cur = self.conn.cursor()
        cur.execute(
            """
            INSERT OR REPLACE INTO projects (id, name, description, createdAt, updatedAt, defaultPermission)
            VALUES (?, ?, ?, ?, ?, ?)
            """,
            (
                project.id,
                project.name,
                project.description,
                project.createdAt,
                project.updatedAt,
                project.defaultPermission.value,
            ),
        )
        self.conn.commit()

    def save_run(self, run: Run) -> None:
        cur = self.conn.cursor()
        cur.execute(
            """
            INSERT OR REPLACE INTO runs (id, projectId, status, startedAt, completedAt, artifactIds, log)
            VALUES (?, ?, ?, ?, ?, ?, ?)
            """,
            (
                run.id,
                run.projectId,
                run.status.value,
                run.startedAt,
                run.completedAt,
                json.dumps(run.artifactIds),
                run.log,
            ),
        )
        self.conn.commit()

    def save_artifact(self, artifact: Artifact) -> None:
        cur = self.conn.cursor()
        cur.execute(
            """
            INSERT OR REPLACE INTO artifacts (id, runId, kind, path, sha256, size, mimeType, createdAt)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                artifact.id,
                artifact.runId,
                artifact.kind.value,
                artifact.path,
                artifact.sha256,
                artifact.size,
                artifact.mimeType,
                artifact.createdAt,
            ),
        )
        self.conn.commit()

    def get_run(self, run_id: str) -> Optional[Run]:
        cur = self.conn.cursor()
        cur.execute("SELECT * FROM runs WHERE id = ?", (run_id,))
        row = cur.fetchone()
        if not row:
            return None
        (
            _id,
            projectId,
            status,
            startedAt,
            completedAt,
            artifactIds_json,
            log,
        ) = row
        return Run(
            id=_id,
            projectId=projectId,
            status=RunStatus(status),
            startedAt=startedAt,
            completedAt=completedAt,
            artifactIds=json.loads(artifactIds_json),
            log=log,
        )

    def list_artifacts_for_run(self, run_id: str) -> List[Artifact]:
        cur = self.conn.cursor()
        cur.execute("SELECT * FROM artifacts WHERE runId = ?", (run_id,))
        rows = cur.fetchall()
        artifacts = []
        for (
            _id,
            _runId,
            kind,
            path,
            sha256,
            size,
            mimeType,
            createdAt,
        ) in rows:
            artifacts.append(
                Artifact(
                    id=_id,
                    runId=_runId,
                    kind=ArtifactKind(kind),
                    path=path,
                    sha256=sha256,
                    size=size,
                    mimeType=mimeType,
                    createdAt=createdAt,
                )
            )
        return artifacts

    def close(self) -> None:
        """Close the underlying SQLite connection."""
        self.conn.close()


__all__ = [
    "Project",
    "Run",
    "Artifact",
    "PlanStep",
    "ExecutionMetadata",
    "AgentEvent",
    "AgentEventType",
    "ProviderError",
    "KernelError",
    "SecurityError",
    "PermissionDecision",
    "ArtifactStore",
    "RunStatus",
    "PermissionProfile",
    "ArtifactKind",
    "_generate_uuid",
    "_now_ms",
    "compute_sha256",
]