import { z } from "zod";

/**
 * Role of a chat message.
 */
export type Role = "system" | "user" | "assistant";

/**
 * Single chat message in OpenAI format.
 */
export interface Message {
  /** Sender role. */
  role: Role;
  /** Message content. */
  content: string;
}

/**
 * Zod schema for Message validation.
 */
export const MessageSchema = z.object({
  role: z.enum(["system", "user", "assistant"]),
  content: z.string().min(1, "Message content cannot be empty"),
});

/**
 * Normalized internal representation of an incoming request.
 */
export interface NormalizedRequest {
  /** Unique request identifier (UUID). */
  id: string;
  /** Canonical model name, e.g. "gemini-1.5-pro". */
  model: string;
  /** Chat history. */
  messages: Message[];
  /** Sampling temperature, 0‑1 range. */
  temperature: number;
  /** Whether the client expects a streaming response. */
  stream: boolean;
  /** Optional caller‑provided context. */
  metadata?: Record<string, unknown>;
}

/**
 * Zod schema that parses and validates the payload of any supported API flavour
 * and produces a NormalizedRequest.
 */
export const NormalizedRequestSchema = z.object({
  id: z.string().uuid(),
  model: z.string().min(1, "Model name required"),
  messages: z.array(MessageSchema).min(1, "At least one message required"),
  temperature: z
    .number()
    .min(0, "Temperature must be >= 0")
    .max(1, "Temperature must be <= 1")
    .default(0.7),
  stream: z.boolean().default(false),
  metadata: z.record(z.any()).optional(),
});

/**
 * Prompt structure required by Gemini Web.
 */
export interface Prompt {
  /** Ordered list of messages, including system instructions if any. */
  messages: Message[];
}

/**
 * Payload sent to Gemini Web.
 */
export interface GeminiPayload {
  /** Gemini model identifier. */
  model: string;
  /** Prompt composed of messages. */
  prompt: Prompt;
  /** Sampling temperature. */
  temperature: number;
  /** Whether Gemini should stream the response. */
  stream: boolean;
}

/**
 * Zod schema for GeminiPayload.
 */
export const GeminiPayloadSchema = z.object({
  model: z.string().min(1, "Gemini model required"),
  prompt: z.object({
    messages: z.array(MessageSchema).min(1, "Prompt must contain at least one message"),
  }),
  temperature: z
    .number()
    .min(0, "Temperature must be >= 0")
    .max(1, "Temperature must be <= 1")
    .default(0.7),
  stream: z.boolean().default(false),
});

/**
 * Individual choice returned by the API.
 */
export interface Choice {
  /** The assistant message (or delta when streaming). */
  message: Message;
  /** Reason the model stopped generating. */
  finish_reason: string;
  /** Index of the choice in the array. */
  index: number;
  /** Partial delta for streaming responses (optional). */
  delta?: Partial<Message>;
}

/**
 * Token usage statistics.
 */
export interface Usage {
  /** Number of tokens in the prompt. */
  prompt_tokens: number;
  /** Number of tokens generated by the model. */
  completion_tokens: number;
  /** Total tokens consumed. */
  total_tokens: number;
}

/**
 * Unified API response emitted to the client.
 */
export interface ApiResponse {
  /** Echoes the request id. */
  id: string;
  /** Fixed value "chat.completion". */
  object: "chat.completion";
  /** Unix epoch seconds when the response was generated. */
  created: number;
  /** Array of generated choices. */
  choices: Choice[];
  /** Optional usage statistics. */
  usage?: Usage;
}

/**
 * Zod schema for ApiResponse (used mainly for testing / type‑guarding).
 */
export const ApiResponseSchema = z.object({
  id: z.string().uuid(),
  object: z.literal("chat.completion"),
  created: z.number().int(),
  choices: z.array(
    z.object({
      message: MessageSchema,
      finish_reason: z.string(),
      index: z.number().int(),
      delta: z
        .object({
          role: z.enum(["system", "user", "assistant"]).optional(),
          content: z.string().optional(),
        })
        .partial()
        .optional(),
    })
  ),
  usage: z
    .object({
      prompt_tokens: z.number().int(),
      completion_tokens: z.number().int(),
      total_tokens: z.number().int(),
    })
    .optional(),
});

/**
 * Model capability description cached by CacheManager.
 */
export interface ModelInfo {
  /** Model identifier. */
  name: string;
  /** Hard token limit for the model. */
  maxTokens: number;
  /** Whether the model supports streaming. */
  supportsStreaming: boolean;
  /** Human‑readable description (optional). */
  description?: string;
}

/**
 * Zod schema for ModelInfo.
 */
export const ModelInfoSchema = z.object({
  name: z.string().min(1),
  maxTokens: z.number().int().positive(),
  supportsStreaming: z.boolean(),
  description: z.string().optional(),
});

/**
 * Context attached to each request for logging / tracing.
 */
export interface RequestContext {
  /** Unique identifier for the request (same as NormalizedRequest.id). */
  requestId: string;
  /** Remote IP address of the caller. */
  ip: string;
  /** User‑Agent header if present. */
  userAgent?: string;
  /** Milliseconds timestamp when processing started. */
  startTime: number;
}

/**
 * Standard error payload returned to clients.
 */
export interface ApiError {
  error: {
    /** Machine‑readable error code. */
    code: string;
    /** Human‑readable description. */
    message: string;
  };
}

/**
 * Zod schema for ApiError.
 */
export const ApiErrorSchema = z.object({
  error: z.object({
    code: z.string(),
    message: z.string(),
  }),
});

/**
 * Helper to create a JSON‑serializable error response.
 *
 * @param code Machine‑readable error identifier.
 * @param message Human‑readable description.
 * @returns ApiError object.
 */
export function createApiError(code: string, message: string): ApiError {
  return { error: { code, message } };
}

/**
 * Chunk emitted by StreamProcessor for SSE responses.
 *
 * The `data` field contains a JSON string that matches the subset of
 * `ApiResponse` required for streaming (typically a single `Choice` with a delta).
 */
export interface ApiChunk {
  /** JSON stringified partial response. */
  data: string;
}

/**
 * Zod schema for a streaming chunk (used by StreamProcessor tests).
 */
export const ApiChunkSchema = z.object({
  data: z.string(),
});

/**
 * Union type for all supported upstream adapters.
 * Currently only GeminiAdapter is implemented, but the type is kept extensible.
 */
export type AdapterName = "gemini";

/**
 * Export a map of supported adapters to their canonical identifiers.
 */
export const SupportedAdapters: Record<AdapterName, string> = {
  gemini: "gemini",
};

/**
 * Runtime validation utilities.
 *
 * These functions are thin wrappers around Zod schemas that throw a
 * `ZodError` with a consistent shape. They are used throughout the codebase
 * to keep validation logic in a single place.
 */
export function validateNormalizedRequest(
  data: unknown
): NormalizedRequest {
  return NormalizedRequestSchema.parse(data);
}

export function validateGeminiPayload(
  data: unknown
): GeminiPayload {
  return GeminiPayloadSchema.parse(data);
}

export function validateApiResponse(
  data: unknown
): ApiResponse {
  return ApiResponseSchema.parse(data);
}

export function validateModelInfo(
  data: unknown
): ModelInfo {
  return ModelInfoSchema.parse(data);
}

export function validateApiChunk(
  data: unknown
): ApiChunk {
  return ApiChunkSchema.parse(data);
}