import { JwtPayload } from "jsonwebtoken";

/**
 * Unique identifier for a session.
 */
export type SessionId = string;

/**
 * Unique identifier for a user.
 */
export type UserId = string;

/**
 * Unique identifier for a stroke.
 */
export type StrokeId = string;

/**
 * Represents a single vector stroke drawn by a user.
 */
export interface Stroke {
  /** UUID of the stroke */
  id: StrokeId;
  /** Array of [x, y] points */
  path: number[][];
  /** Stroke colour in hex */
  color: string;
  /** Stroke width in pixels */
  width: number;
  /** Unix timestamp (ms) when the stroke was created */
  timestamp: number;
  /** Identifier of the user who created the stroke */
  userId: UserId;
}

/**
 * Minimal user representation used by the auth middleware.
 */
export interface User {
  id: UserId;
  name: string;
  /** JWT payload after verification */
  payload: JwtPayload;
}

/**
 * Session model – holds participants and stroke history.
 */
export interface Session {
  id: SessionId;
  /** Map of userId → User */
  participants: Map<UserId, User>;
  /** Ordered list of strokes for this session */
  strokes: Stroke[];
  /** Version number that increments on each mutation */
  version: number;
}

/**
 * Request sent to an LLM provider.
 */
export interface LLMRequest {
  sessionId: SessionId;
  strokes: Stroke[];
  /** Optional additional context */
  context?: string;
}

/**
 * Response received from an LLM provider.
 */
export interface LLMResponse {
  /** Textual answer generated by the LLM */
  answer: string;
  /** Identifier of the request for correlation */
  requestId: string;
}

/**
 * Number of retry attempts for transient failures.
 */
export const RETRY_LIMIT = 3;

/**
 * Simple exponential back‑off helper.
 */
export function exponentialBackoff(attempt: number): number {
  const base = 100; // 100 ms base delay
  return base * Math.pow(2, attempt);
}
