import { readFileSync, existsSync } from "fs";
import { createHash } from "crypto";

/**
 * Represents a single file modification within a ChangeSet.
 */
export interface ChangeFile {
  /** Absolute or relative path to the file. */
  path: string;
  /** SHA‑256 hash of the file content before the change. */
  oldHash: string;
  /** Full new content after the change. */
  newContent: string;
}

/**
 * Collection of file modifications together with metadata.
 */
export interface ChangeSet {
  files: ChangeFile[];
  /** Identifier of the author of the change set. */
  author: string;
}

/**
 * Result of a read operation.
 */
export interface FileContentResult {
  content: string;
  hash: string;
}

/**
 * Options for reading a file.
 */
export interface ReadOpts {
  encoding?: BufferEncoding;
}

/**
 * Result of a write operation.
 */
export interface WriteResult {
  path: string;
  success: boolean;
  error?: string;
}

/**
 * Result of applying a ChangeSet.
 */
export interface ApplyResult {
  applied: boolean;
  errors?: string[];
}

/**
 * Verdict returned by a policy evaluation.
 */
export interface Verdict {
  allowed: boolean;
  reasons?: string[];
}

/**
 * Function signature for a policy.
 */
export type Policy = (changeSet: ChangeSet) => Promise<Verdict>;

/**
 * Shape of the response returned by the AI connector.
 */
export interface AIResponse {
  /** Raw text generated by the model. */
  content: string;
  /** Optional metadata. */
  metadata?: Record<string, unknown>;
}
